"""Author the shipped fictional population catalogue; no network or runtime dependency."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
pools={}
def pool(key,given,family,style='given_family'):
    pools[key]=dict(given=given.split('|'),family=family.split('|'),style=style)
pool('english','Oliver|George|Harry|Jack|Jacob|Noah|Charlie|Oscar|James|William|Thomas|Alfie|Henry|Leo|Freddie|Arthur|Archie|Theo|Finley|Joshua|Ethan|Isaac|Alexander|Joseph|Edward|Samuel|Daniel|Benjamin|Nathan|Max','Smith|Jones|Taylor|Brown|Williams|Wilson|Johnson|Davies|Robinson|Wright|Thompson|Evans|Walker|White|Roberts|Green|Hall|Wood|Jackson|Clarke|Mason|Turner|Hughes|Edwards|Hill|Moore|Cooper|Ward|Bennett|Reed')
pool('irish','Seán|Cian|Oisín|Darragh|Conor|Finn|Ronan|Tadhg|Cillian|Eoin|Fionn|Niall|Patrick|Liam|Declan|Aidan','Murphy|Kelly|Byrne|Ryan|O’Brien|Walsh|O’Sullivan|Doyle|McCarthy|Gallagher|O’Connor|Kennedy|Lynch|Murray|Quinn|Reilly')
pool('welsh','Dylan|Rhys|Ieuan|Owain|Gareth|Bryn|Evan|Gethin|Iwan|Aled|Dafydd|Harri|Llyr|Morgan|Tomos|Ellis','Jones|Davies|Evans|Thomas|Williams|Griffiths|Hughes|Price|Lloyd|Rees|Powell|Parry|Vaughan|Roberts|Lewis|Jenkins')
pool('scottish','Alasdair|Callum|Euan|Fraser|Hamish|Lachlan|Lewis|Angus|Iain|Finlay|Gregor|Duncan|Ross|Cameron|Blair|Jamie','Campbell|Stewart|MacDonald|MacLeod|Fraser|Robertson|Murray|Anderson|Scott|Reid|Wallace|Graham|Ferguson|Douglas|MacKenzie|Grant')
pool('french','Lucas|Hugo|Louis|Gabriel|Arthur|Jules|Raphaël|Léo|Maxime|Antoine|Étienne|Mathis|Clément|Baptiste|Romain|Julien','Martin|Bernard|Dubois|Thomas|Robert|Richard|Petit|Durand|Leroy|Moreau|Simon|Laurent|Lefebvre|Michel|Garcia|Roux')
pool('german','Lukas|Leon|Paul|Finn|Felix|Jonas|Elias|Ben|Niklas|Moritz|Florian|Tobias|Julian|Maximilian|Anton|Sebastian','Müller|Schmidt|Schneider|Fischer|Weber|Meyer|Wagner|Becker|Schulz|Hoffmann|Schäfer|Koch|Bauer|Richter|Klein|Wolf')
pool('spanish','Alejandro|Daniel|Pablo|Álvaro|Adrián|David|Javier|Diego|Sergio|Marcos|Manuel|Antonio|Miguel|Carlos|Raúl|Hugo','García|Rodríguez|González|Fernández|López|Martínez|Sánchez|Pérez|Gómez|Martín|Jiménez|Ruiz|Hernández|Díaz|Moreno|Muñoz','double_family')
pool('portuguese','João|Miguel|Diogo|Tiago|Pedro|Rafael|Gonçalo|André|Tomás|Francisco|Duarte|Afonso|Guilherme|Rodrigo|Lucas|Gabriel','Silva|Santos|Ferreira|Pereira|Oliveira|Costa|Rodrigues|Martins|Jesus|Sousa|Fernandes|Gonçalves|Gomes|Lopes|Marques|Almeida','double_family')
pool('italian','Lorenzo|Francesco|Alessandro|Matteo|Leonardo|Andrea|Gabriele|Riccardo|Federico|Davide|Marco|Luca|Giovanni|Simone|Filippo|Niccolò','Rossi|Russo|Ferrari|Esposito|Bianchi|Romano|Colombo|Ricci|Marino|Greco|Bruno|Gallo|Conti|De Luca|Costa|Mancini')
pool('dutch','Daan|Sem|Bram|Luuk|Finn|Lars|Niels|Jasper|Thijs|Jesse|Sven|Joris|Ruben|Stijn|Floris|Willem','De Jong|Jansen|De Vries|Van den Berg|Van Dijk|Bakker|Janssen|Visser|Smit|Meijer|De Boer|Mulder|De Groot|Bos|Vos|Peters')
pool('nordic','Erik|Lars|Anders|Johan|Magnus|Emil|Oscar|Axel|Viktor|Elias|Nils|Gustav|Oskar|Henrik|Sven|Mikkel','Andersson|Johansson|Karlsson|Nilsson|Eriksson|Larsen|Hansen|Nielsen|Jensen|Olsen|Berg|Lindberg|Lund|Dahl|Holm|Sørensen')
pool('finnish','Eetu|Elias|Onni|Väinö|Lauri|Mikko|Antti|Jussi|Juho|Oskari|Aapo|Aatu|Vilho|Ilmari|Tuomas|Aleksi','Korhonen|Virtanen|Mäkinen|Nieminen|Mäkelä|Hämäläinen|Laine|Heikkinen|Koskinen|Järvinen|Lehtonen|Lehtinen|Saarinen|Salminen|Heinonen|Niemi')
pool('icelandic','Jón|Aron|Bjarni|Einar|Gunnar|Hákon|Ólafur|Ragnar|Sigurður|Stefán|Viktor|Benedikt|Baldur|Kári|Kristján|Magnús','Jónsson|Aronsson|Bjarnason|Einarsson|Gunnarsson|Hákonarson|Ólafsson|Ragnarsson|Sigurðsson|Stefánsson|Viktorsson|Benediktsson|Baldursson|Kárason|Kristjánsson|Magnússon')
pool('polish','Jakub|Kacper|Filip|Szymon|Jan|Michał|Adam|Mateusz|Piotr|Paweł|Bartosz|Wojciech|Tomasz|Kamil|Marcin|Krzysztof','Nowak|Kowalski|Wiśniewski|Wójcik|Kowalczyk|Kamiński|Lewandowski|Zieliński|Szymański|Woźniak|Dąbrowski|Kozłowski|Jankowski|Mazur|Kwiatkowski|Wojciechowski')
pool('czech','Jakub|Jan|Tomáš|Adam|Lukáš|Matěj|Filip|Vojtěch|Ondřej|Petr|David|Michal|Martin|Josef|Daniel|Šimon','Novák|Svoboda|Novotný|Dvořák|Černý|Procházka|Kučera|Veselý|Horák|Němec|Pokorný|Marek|Pospíšil|Hájek|Král|Jelínek')
pool('balkan','Luka|Marko|Nikola|Ivan|Stefan|Petar|Filip|Miloš|Dušan|Nemanja|Aleksandar|Milan|Dejan|Dragan|Andrej|Matej','Petrović|Jovanović|Nikolić|Marković|Đorđević|Stojanović|Ilić|Pavlović|Popović|Kovačević|Babić|Marić|Jurić|Horvat|Vuković|Knežević')
pool('romanian','Andrei|Alexandru|Mihai|Ștefan|Gabriel|Cristian|Ionuț|Vlad|Rareș|Radu|Darius|Florin|Ciprian|Adrian|Claudiu|Daniel','Popescu|Popa|Ionescu|Dumitrescu|Stoica|Stan|Dobre|Marin|Radu|Gheorghe|Diaconu|Tudor|Preda|Dinu|Niculescu|Munteanu')
pool('hungarian','Bence|Máté|Levente|Ádám|Dávid|Balázs|Dominik|Dániel|Benedek|Gergő|Zoltán|Péter|Tamás|András|Attila|Miklós','Nagy|Kovács|Tóth|Szabó|Horváth|Varga|Kiss|Molnár|Németh|Farkas|Balogh|Papp|Takács|Juhász|Lakatos|Mészáros','family_given')
pool('greek','Giorgos|Nikos|Dimitris|Giannis|Kostas|Vasilis|Panagiotis|Christos|Stavros|Alexandros|Andreas|Marios|Michalis|Sotiris|Theodoros|Petros','Papadopoulos|Nikolaou|Georgiou|Dimitriou|Ioannou|Pappas|Karagiannis|Vasileiou|Papadakis|Alexiou|Konstantinou|Antoniou|Makris|Lazaridis|Michailidis|Christou')
pool('turkish','Emir|Yusuf|Mustafa|Mehmet|Ahmet|Ali|Ömer|Eren|Burak|Kerem|Arda|Mert|Can|Emre|Deniz|Kaan','Yılmaz|Kaya|Demir|Şahin|Çelik|Yıldız|Yıldırım|Öztürk|Aydın|Arslan|Doğan|Kılıç|Aslan|Çetin|Kara|Koç')
pool('russian','Aleksandr|Dmitri|Maksim|Ivan|Mikhail|Nikita|Artem|Andrei|Sergei|Kirill|Pavel|Roman|Viktor|Denis|Ilya|Yegor','Ivanov|Smirnov|Kuznetsov|Popov|Sokolov|Lebedev|Kozlov|Novikov|Morozov|Petrov|Volkov|Solovyov|Vasilyev|Zaitsev|Pavlov|Semyonov')
pool('ukrainian','Oleksandr|Dmytro|Maksym|Andrii|Mykhailo|Artem|Bohdan|Denys|Ivan|Yaroslav|Vladyslav|Serhii|Pavlo|Roman|Viktor|Taras','Shevchenko|Kovalenko|Bondarenko|Tkachenko|Kravchenko|Kovalchuk|Melnyk|Boyko|Savchenko|Polishchuk|Shevchuk|Tkachuk|Moroz|Marchenko|Pavlenko|Rudenko')
pool('baltic','Jonas|Lukas|Mantas|Tomas|Domas|Paulius|Arnas|Rokas|Matas|Dovydas|Jānis|Artūrs|Roberts|Rasmus|Karl|Markus','Kazlauskas|Jankauskas|Petrauskas|Stankevičius|Vasiliauskas|Žukauskas|Paulauskas|Urbonas|Bērziņš|Kalniņš|Ozoliņš|Liepiņš|Tamm|Saar|Sepp|Kask')
pool('albanian','Arben|Ardit|Besnik|Dritan|Erion|Ilir|Luan|Mentor|Sokol|Valon|Ylli|Altin|Blerim|Faton|Gent|Visar','Hoxha|Shehu|Dervishi|Krasniqi|Berisha|Gashi|Shala|Kelmendi|Mustafa|Rama|Prifti|Leka|Basha|Bytyqi|Hoti|Kola')
pool('georgian','Giorgi|Luka|Nika|Davit|Saba|Irakli|Levan|Tornike|Zurab|Giga|Guram|Beka|Sandro|Vakhtang|Shota|Merab','Beridze|Kapanadze|Gelashvili|Maisuradze|Giorgadze|Lomidze|Tsiklauri|Dvali|Chkheidze|Kiknadze|Japaridze|Kvaratskhelia|Kalandadze|Gogoladze|Tsereteli|Metreveli')
pool('armenian','Aram|Armen|Gor|Hayk|Narek|Tigran|Vahan|Artur|Davit|Levon|Hovhannes|Karen|Ashot|Samvel|Suren|Ruben','Sargsyan|Harutyunyan|Hovhannisyan|Hakobyan|Grigoryan|Petrosyan|Vardanyan|Gevorgyan|Karapetyan|Manukyan|Avetisyan|Ghazaryan|Martirosyan|Simonyan|Mkrtchyan|Stepanyan')
pool('arabic','Mohamed|Ahmed|Omar|Youssef|Ali|Hassan|Hussein|Ibrahim|Khalid|Karim|Yassine|Amine|Walid|Rami|Tariq|Sami','Haddad|Mansour|Nasser|Saleh|Khalil|Hamdan|Farah|Darwish|Saad|Habib|Fahmy|Aziz|Idrissi|Benali|Moussa|Rahmani')
pool('hebrew','Noam|Itai|Ariel|Eitan|Daniel|David|Yonatan|Uri|Omer|Lior|Amit|Nadav|Eyal|Alon|Yair|Roee','Cohen|Levi|Mizrahi|Peretz|Biton|Dahan|Avraham|Friedman|Azoulay|Amar|Gabay|Katz|Yosef|Tal|Barak|Shapiro')
pool('persian','Amir|Ali|Reza|Hossein|Mehdi|Arman|Saman|Farhad|Navid|Parsa|Kian|Pouya|Omid|Dariush|Sina|Shahin','Mohammadi|Hosseini|Ahmadi|Rezaei|Karimi|Mousavi|Rahimi|Jafari|Kazemi|Moradi|Ebrahimi|Alizadeh|Hashemi|Ghasemi|Bahrami|Shirazi')
pool('turkic','Aziz|Timur|Rustam|Bekzod|Sardor|Jasur|Alisher|Doston|Dilshod|Sherzod|Ulugbek|Islom|Akmal|Anvar|Mirzo|Kamol','Karimov|Yusupov|Tursunov|Rahimov|Ismailov|Abdullayev|Nazarov|Saidov|Mirzayev|Ergashev|Rakhmonov|Azimov|Sharipov|Mamatov|Rustamov|Ibragimov')
pool('hindi','Aarav|Arjun|Aditya|Rohan|Rahul|Vikram|Karan|Nikhil|Ankit|Sanjay|Ravi|Deepak|Manish|Amit|Vivek|Pranav','Sharma|Verma|Singh|Gupta|Kumar|Patel|Yadav|Chauhan|Joshi|Mishra|Pandey|Rao|Mehta|Jain|Kapoor|Nair')
pool('tamil','Arun|Karthik|Suresh|Vijay|Prakash|Dinesh|Saravanan|Ganesh|Senthil|Ramesh|Bala|Kumar|Ravi|Sathish|Pradeep|Ashwin','Rajendran|Subramanian|Krishnan|Raman|Murugan|Sundaram|Natarajan|Balasubramanian|Shanmugam|Ramasamy|Velu|Perumal|Mani|Pillai|Selvam|Arumugam')
pool('bengali','Arif|Rahim|Hasan|Rakib|Sajid|Imran|Fahim|Tanvir|Soham|Anirban|Sourav|Arindam|Subhas|Debashis|Ranjan|Suman','Rahman|Ahmed|Hossain|Islam|Khan|Alam|Chowdhury|Sarkar|Das|Roy|Sen|Dutta|Bose|Mitra|Saha|Biswas')
pool('urdu','Ahmed|Ali|Hassan|Usman|Hamza|Bilal|Fahad|Imran|Kamran|Salman|Farhan|Adnan|Zain|Adeel|Danish|Waqas','Khan|Ahmed|Ali|Hussain|Malik|Iqbal|Butt|Sheikh|Raza|Qureshi|Chaudhry|Shah|Javed|Siddiqui|Abbasi|Akhtar')
pool('nepali','Suman|Bikash|Rajan|Prakash|Dipak|Santosh|Anil|Sagar|Ramesh|Binod|Manoj|Kiran|Nabin|Suraj|Ashish|Bibek','Shrestha|Gurung|Tamang|Rai|Limbu|Thapa|Karki|Adhikari|Acharya|Bhandari|Poudel|Khadka|Basnet|Magar|Koirala|Rijal')
pool('sinhalese','Nuwan|Chamara|Thilina|Kasun|Dinesh|Lahiru|Dilshan|Gayan|Roshan|Sampath|Chathura|Isuru|Pradeep|Dasun|Ravindu|Sajith','Perera|Fernando|Silva|Mendis|Jayasinghe|Dissanayake|Wijesinghe|Bandara|Gunawardena|Senanayake|Herath|Weerasinghe|Karunaratne|Ratnayake|Abeysekera|Rajapaksa')
pool('chinese','Wei|Jun|Ming|Tao|Hao|Lei|Jie|Bo|Feng|Qiang|Yong|Bin|Chao|Peng|Chen|Kai','Wang|Li|Zhang|Liu|Chen|Yang|Huang|Zhao|Wu|Zhou|Xu|Sun|Ma|Zhu|Hu|Guo','family_given')
pool('japanese','Haruto|Yuto|Sota|Ren|Yuki|Kaito|Riku|Daiki|Takumi|Shota|Hiroki|Tsubasa|Ryota|Kenta|Sho|Yuma','Sato|Suzuki|Takahashi|Tanaka|Watanabe|Ito|Yamamoto|Nakamura|Kobayashi|Kato|Yoshida|Yamada|Sasaki|Yamaguchi|Matsumoto|Inoue','family_given')
pool('korean','Min-jun|Seo-jun|Ji-ho|Do-yun|Ha-jun|Jun-seo|Si-woo|Ye-jun|Ju-won|Hyun-woo|Ji-hun|Sung-min|Jae-hyun|Min-su|Seung-ho|Dong-hyun','Kim|Lee|Park|Choi|Jung|Kang|Cho|Yoon|Jang|Lim|Han|Oh|Seo|Shin|Kwon|Hwang','family_given')
pool('vietnamese','Minh|Anh|Duc|Huy|Khang|Bao|Phuc|Nam|Quang|Tuan|Long|Thanh|Hung|Son|Duy|Hai','Nguyễn|Trần|Lê|Phạm|Hoàng|Huỳnh|Phan|Vũ|Võ|Đặng|Bùi|Đỗ|Hồ|Ngô|Dương|Lý','family_given')
pool('thai','Somchai|Anan|Arthit|Chai|Kittipong|Nattapong|Piyawat|Sakchai|Somsak|Thanawat|Weerachai|Wichai|Phuwin|Krit|Narin|Teerapat','Sukjai|Srisai|Thongchai|Wongsa|Saengsuwan|Boonmee|Kaewmanee|Chaisri|Intara|Phromma|Khamdee|Chantana|Saetang|Wongchai|Suwan|Thongsuk')
pool('indonesian','Agus|Budi|Dimas|Eko|Fajar|Hadi|Indra|Joko|Rizky|Aditya|Bayu|Dedi|Gilang|Wahyu|Yoga|Rian','Pratama|Saputra|Wijaya|Santoso|Setiawan|Hidayat|Nugroho|Wibowo|Kurniawan|Putra|Ramadhan|Firmansyah|Susanto|Gunawan|Prasetyo|Permana')
pool('malay','Amir|Hakim|Hafiz|Faiz|Azlan|Azmi|Farid|Rizal|Shahrul|Zulkifli|Khairul|Aiman|Irfan|Haziq|Syafiq|Firdaus','Abdullah|Ibrahim|Ismail|Hassan|Omar|Ahmad|Rahman|Yusof|Hamid|Osman|Ali|Abdul Aziz|Zainal|Salleh|Razak|Musa')
pool('filipino','Jose|Juan|Miguel|Paolo|Carlo|Rafael|Angelo|Luis|Mark|John|Jayson|Christian|Marco|Gabriel|Enzo|Antonio','Santos|Reyes|Cruz|Bautista|Ocampo|Garcia|Mendoza|Torres|Dela Cruz|Ramos|Aquino|Flores|Castillo|Rivera|Gonzales|Villanueva')
pool('mongolian','Bat|Bold|Dorj|Temuulen|Tengis|Bilguun|Munkh|Batsaikhan|Batbayar|Erdene|Enkh|Bayar|Ganbold|Altan|Otgon|Anand','Batmunkh|Dorj|Enkhbat|Batbayar|Baatar|Ganbold|Tseren|Davaajav|Erdenebat|Bayarsaikhan|Jargal|Purev|Tumur|Naran|Sukhbat|Lkhagva','family_given')
pool('khmer','Dara|Sokha|Sopheap|Vannak|Rithy|Sovann|Visal|Sopheak|Chhay|Bunthorn|Sothea|Piseth|Virak|Sambath|Sovan|Chenda','Sok|Chan|Chea|Kem|Long|Lim|Ly|Heng|Chhun|Phan|Seng|Som|Sun|Hun|Touch|You','family_given')
pool('burmese','Aung|Min|Kyaw|Htet|Zaw|Thant|Win|Soe|Myo|Naing|Tun|Ye|Hein|Nyein|Lin|Thet','Aung|Min|Kyaw|Htet|Zaw|Thant|Win|Soe|Myo|Naing|Tun|Ye|Hein|Nyein|Lin|Thet')
pool('wolof','Moussa|Ibrahima|Mamadou|Cheikh|Ousmane|Lamine|Abdoulaye|Samba|Pape|Saliou|Malick|Amadou|Babacar|Modou|Omar|Demba','Diop|Ndiaye|Fall|Gueye|Sow|Diallo|Ba|Sarr|Diouf|Seck|Cissé|Faye|Touré|Camara|Dieng|Sy')
pool('akan','Kwame|Kofi|Kwabena|Kwaku|Yaw|Kwesi|Kojo|Nana|Kwasi|Akwasi|Kwadwo|Afriyie|Agyeman|Osei|Kweku|Nii','Mensah|Owusu|Osei|Boateng|Acheampong|Asante|Adjei|Agyemang|Opoku|Appiah|Bonsu|Amoah|Antwi|Asare|Agyei|Sarpong')
pool('yoruba','Ade|Tunde|Femi|Segun|Dele|Babatunde|Oluwaseun|Ayodele|Olamide|Temitope|Tobi|Kunle|Seyi|Dayo|Damilola|Akin','Adeyemi|Adebayo|Ogunleye|Adesina|Oladipo|Olatunji|Akinwale|Falade|Ojo|Balogun|Adeleke|Alabi|Lawal|Afolabi|Oke|Olaleye')
pool('igbo','Chinedu|Chukwudi|Ikenna|Emeka|Obinna|Nnamdi|Ifeanyi|Chidi|Chibuike|Uche|Chisom|Nonso|Kelechi|Tochukwu|Ikechukwu|Chimezie','Okafor|Okeke|Eze|Okonkwo|Nwankwo|Nwachukwu|Nwosu|Obi|Onyeka|Okoro|Ibe|Nnamani|Umeh|Anyanwu|Ezeh|Agu')
pool('hausa','Musa|Ibrahim|Sani|Umar|Aliyu|Yusuf|Bello|Abdullahi|Hassan|Suleiman|Kabiru|Aminu|Usman|Garba|Haruna|Lawal','Abubakar|Mohammed|Ibrahim|Suleiman|Bello|Abdullahi|Usman|Garba|Haruna|Lawal|Danladi|Yakubu|Sani|Umar|Musa|Yusuf')
pool('swahili','Juma|Baraka|Hamisi|Omari|Rashidi|Salim|Bakari|Hassan|Said|Rajabu|Issa|Musa|Nuru|Abdallah|Mwaniki|Mwangi','Mussa|Juma|Said|Mohamed|Hassan|Bakari|Salum|Mwakalinga|Mwinyi|Khamis|Mashauri|Nyerere|Mboya|Odhiambo|Omondi|Otieno')
pool('amharic','Abel|Dawit|Daniel|Yonas|Samuel|Henok|Tesfaye|Bereket|Girma|Mulugeta|Solomon|Getachew|Tadesse|Amanuel|Eyob|Fikru','Tesfaye|Bekele|Getachew|Tadesse|Girma|Haile|Mekonnen|Alemu|Abebe|Kebede|Desta|Tsegaye|Ayele|Teferi|Assefa|Wolde')
pool('somali','Abdi|Ahmed|Ali|Hassan|Hussein|Mohamed|Omar|Yusuf|Abdullahi|Ismail|Ibrahim|Farah|Jama|Warsame|Bashir|Osman','Mohamed|Ahmed|Ali|Hassan|Omar|Yusuf|Abdi|Farah|Jama|Warsame|Bashir|Osman|Adan|Nur|Roble|Guled')
pool('southern_african','Sipho|Thabo|Themba|Sibusiso|Bongani|Mandla|Vusi|Sizwe|Mpho|Kabelo|Lerato|Tebogo|Tumelo|Tshepo|Lungelo|Siyabonga','Dlamini|Nkosi|Ndlovu|Khumalo|Mokoena|Molefe|Mabena|Mahlangu|Mthembu|Maseko|Sithole|Zulu|Dube|Moyo|Mhlanga|Ncube')
pool('central_african','Jean|Alain|Patrick|Fabrice|Serge|Didier|Christian|Cédric|Joseph|Emmanuel|Samuel|Franck|André|Paul|Michel|Blaise','Mbala|Nsimba|Mbuyi|Kabongo|Tshibangu|Ilunga|Mwamba|Kasongo|Moke|Makengo|Ngoma|Moukoko|Nkomo|Essomba|Abega|Ondoa')
pool('malagasy','Andry|Tiana|Hery|Faneva|Fetra|Toky|Tahina|Mamy|Lova|Hasina|Njaka|Aina|Solo|Mickaël|Tsiory|Henintsoa','Rakoto|Rabe|Rajaona|Randrianasolo|Rakotomalala|Rasoanaivo|Randria|Razanakoto|Andrianina|Ravelomanana|Ramaroson|Ratsimba|Ralaivao|Rafaly|Razanadrakoto|Razanamparany')
pool('polynesian','Tane|Manu|Sione|Tavita|Pita|Ioane|Malakai|Viliami|Sami|Latu|Niko|Mika|Iosefa|Paulo|Sefa|Toa','Fetu|Latu|Manu|Tupou|Taumoepeau|Tuipulotu|Vaega|Tui|Vea|Iosefo|Fale|Mata|Moli|Savelio|Toma|Ulu')
pool('melanesian','Jone|Josua|Peni|Samu|Iliesa|Setareki|Tevita|Kini|Mesake|Savenaca|Mosese|Nemani|Ratu|Viliame|Isikeli|Meli','Bale|Roko|Koro|Naivalu|Tawake|Ravulo|Ratu|Kuru|Nadro|Luvu|Vula|Vakuru|Vakacegu|Naisara|Sogo|Tavaga')
pool('dzongkha','Jigme|Tenzin|Sonam|Pema|Karma|Tshering|Ugyen|Kezang|Wangdi|Dorji|Dawa|Namgay|Sangay|Phuntsho|Kinley|Jamyang','Dorji|Wangchuk|Namgyel|Tobgay|Tshering|Norbu|Gyeltshen|Wangdi|Rinchen|Tashi|Choden|Gyatso|Penjor|Dendup|Zangpo|Jamtsho')
pool('lao','Somphone|Khampheng|Bounmy|Bounthavy|Phouthone|Sengdao|Anousone|Souvannasak|Vannasone|Manivone|Khamla|Bounnhang|Thongkham|Sithong|Phouvong|Sombath','Phommasane|Souvannavong|Phanthavong|Keomany|Sisoulith|Vongphachanh|Inthavong|Chanthavong|Sengsavang|Sayavong|Vongsa|Sihanath|Phommalath|Soulivong|Intharath|Keovongsa')
pool('divehi','Mohamed|Ahmed|Ibrahim|Ali|Hassan|Hussain|Ismail|Abdulla|Yusuf|Adam|Fathih|Nashid|Shifau|Ishaq|Niyaz|Ziyad','Rasheed|Shareef|Shiham|Waheed|Shaheem|Didi|Manik|Zahir|Naseem|Latheef|Shakir|Shameem|Fauzee|Saeed|Nazeer|Mahir')
pool('nilotic','Deng|Dut|Majok|Ajak|Bior|Bol|Garang|Kuol|Mabior|Maker|Malual|Mayen|Nhial|Riek|Tut|Wek','Deng|Dut|Majok|Ajak|Bior|Bol|Garang|Kuol|Mabior|Maker|Malual|Mayen|Nhial|Riek|Tut|Wek')
# Each row is authored content, not a claim that every territory has playable leagues.
regions={
'Europe':'''England:english;Scotland:scottish;Wales:welsh;Northern Ireland:irish;Republic of Ireland:irish;Germany:german;France:french;Spain:spanish;Netherlands:dutch;Portugal:portuguese;Italy:italian;Albania:albanian;Andorra:spanish;Armenia:armenian;Austria:german;Azerbaijan:turkic;Belarus:russian;Belgium:dutch;Bosnia and Herzegovina:balkan;Bulgaria:balkan;Croatia:balkan;Cyprus:greek;Czechia:czech;Denmark:nordic;Estonia:baltic;Faroe Islands:nordic;Finland:finnish;Georgia:georgian;Gibraltar:english;Greece:greek;Hungary:hungarian;Iceland:icelandic;Israel:hebrew;Kazakhstan:turkic;Kosovo:albanian;Latvia:baltic;Liechtenstein:german;Lithuania:baltic;Luxembourg:french;Malta:english;Moldova:romanian;Montenegro:balkan;North Macedonia:balkan;Norway:nordic;Poland:polish;Romania:romanian;Russia:russian;San Marino:italian;Serbia:balkan;Slovakia:czech;Slovenia:balkan;Sweden:nordic;Switzerland:german;Türkiye:turkish;Ukraine:ukrainian''',
'South America':'''Argentina:spanish;Bolivia:spanish;Brazil:portuguese;Chile:spanish;Colombia:spanish;Ecuador:spanish;Paraguay:spanish;Peru:spanish;Uruguay:spanish;Venezuela:spanish''',
'North America':'''Anguilla:english;Antigua and Barbuda:english;Aruba:dutch;Bahamas:english;Barbados:english;Belize:english;Bermuda:english;British Virgin Islands:english;Canada:english;Cayman Islands:english;Costa Rica:spanish;Cuba:spanish;Curaçao:dutch;Dominica:english;Dominican Republic:spanish;El Salvador:spanish;Grenada:english;Guatemala:spanish;Guyana:english;Haiti:french;Honduras:spanish;Jamaica:english;Mexico:spanish;Montserrat:english;Nicaragua:spanish;Panama:spanish;Puerto Rico:spanish;Saint Kitts and Nevis:english;Saint Lucia:english;Saint Vincent and the Grenadines:english;Suriname:dutch;Trinidad and Tobago:english;Turks and Caicos Islands:english;USA:english;US Virgin Islands:english''',
'Asia':'''Afghanistan:persian;Australia:english;Bahrain:arabic;Bangladesh:bengali;Bhutan:dzongkha;Brunei:malay;Cambodia:khmer;China:chinese;Chinese Taipei:chinese;Guam:filipino;Hong Kong:chinese;India:hindi;Indonesia:indonesian;Iran:persian;Iraq:arabic;Japan:japanese;Jordan:arabic;Kuwait:arabic;Kyrgyzstan:turkic;Laos:lao;Lebanon:arabic;Macau:chinese;Malaysia:malay;Maldives:divehi;Mongolia:mongolian;Myanmar:burmese;Nepal:nepali;North Korea:korean;Oman:arabic;Pakistan:urdu;Palestine:arabic;Philippines:filipino;Qatar:arabic;Saudi Arabia:arabic;Singapore:chinese;South Korea:korean;Sri Lanka:sinhalese;Syria:arabic;Tajikistan:persian;Thailand:thai;Timor-Leste:portuguese;Turkmenistan:turkic;United Arab Emirates:arabic;Uzbekistan:turkic;Vietnam:vietnamese;Yemen:arabic''',
'Africa':'''Algeria:arabic;Angola:portuguese;Benin:yoruba;Botswana:southern_african;Burkina Faso:wolof;Burundi:swahili;Cameroon:central_african;Cabo Verde:portuguese;Central African Republic:central_african;Chad:arabic;Comoros:swahili;Congo:central_african;DR Congo:central_african;Côte d’Ivoire:akan;Djibouti:somali;Egypt:arabic;Equatorial Guinea:spanish;Eritrea:amharic;Eswatini:southern_african;Ethiopia:amharic;Gabon:central_african;Gambia:wolof;Ghana:akan;Guinea:wolof;Guinea-Bissau:wolof;Kenya:swahili;Lesotho:southern_african;Liberia:english;Libya:arabic;Madagascar:malagasy;Malawi:swahili;Mali:wolof;Mauritania:arabic;Mauritius:hindi;Morocco:arabic;Mozambique:portuguese;Namibia:southern_african;Niger:hausa;Nigeria:yoruba;Rwanda:swahili;São Tomé and Príncipe:portuguese;Senegal:wolof;Seychelles:french;Sierra Leone:english;Somalia:somali;South Africa:southern_african;South Sudan:nilotic;Sudan:arabic;Tanzania:swahili;Togo:akan;Tunisia:arabic;Uganda:swahili;Zambia:swahili;Zimbabwe:southern_african''',
'Oceania':'''American Samoa:polynesian;Cook Islands:polynesian;Fiji:melanesian;New Caledonia:french;New Zealand:english;Papua New Guinea:melanesian;Samoa:polynesian;Solomon Islands:melanesian;Tahiti:polynesian;Tonga:polynesian;Vanuatu:melanesian'''}
import re,unicodedata
aliases={'Republic of Ireland':'ireland','USA':'usa'}
def slug(name):return aliases.get(name,re.sub(r'[^a-z0-9]+','-',unicodedata.normalize('NFKD',name).encode('ascii','ignore').decode().lower()).strip('-'))
active=json.loads((ROOT/'data/nations.json').read_text())['nations'];by_name={n['name']:n for n in active}
nations=[]
for region,content in regions.items():
 for row in content.split(';'):
  name,locale=row.split(':');profile=by_name.get(name)
  nations.append(dict(id=slug(name),name=name,region=region,playable=bool(profile),locales=[dict(pool=locale,weight=100)],clubs=sum(profile['division_sizes']) if profile else 2,cities=profile['cities'] if profile and profile.get('cities') else [],coverage='authored starter pool'))
# Explicit linguistic variety: choices affect names, never talent or personality.
mixtures={'Mauritius':('hindi','french','tamil'),'Belgium':('dutch','french'),'Switzerland':('german','french','italian'),'Canada':('english','french'),'Nigeria':('yoruba','igbo','hausa'),'India':('hindi','tamil','bengali'),'Singapore':('chinese','malay','tamil'),'South Africa':('southern_african','english'),'Sri Lanka':('sinhalese','tamil'),'USA':('english','spanish'),'Brazil':('portuguese',),'Malaysia':('malay','chinese','tamil')}
for n in nations:
 if n['name'] in mixtures:n['locales']=[dict(pool=p,weight=100) for p in mixtures[n['name']]]
assert len(nations)==211,len(nations)
# National identity is not gated by FIFA membership either. Include sovereign
# states without a FIFA team and additional populated territories. Broad shared
# pools remain explicitly provisional content, not cultural completeness claims.
pool('kiribati','Beniamino|David|Ioane|Kaiea|Teburoro|Taneti|Anote|Ieremia|Tebao|Tion|Teatao|Taomati|Tebwe|Teariki|Tevita|Toakai','Tong|Tabai|Tito|Maamau|Ieremia|Teannaki|Onorio|Teaiwa|Tebano|Tamuera|Tooma|Baiteke|Kabure|Katoa|Bureimoa|Reiher')
pool('micronesian','David|John|Thomas|Peter|Joseph|Elias|Paul|James|Nakamura|Kuniwo|Anjain|Nero|Rubin|Tosiwo|Bailey|Surangel','Remengesau|Whipps|Toribiong|Nakamura|Olkeriil|Mori|Panuelo|Christian|Falcam|Nakayama|Kabua|Loeak|Note|Heine|Scotty|Adeang')
pool('tuvaluan','Sopoaga|Kausea|Feleti|Toafa|Maatia|Enele|Iakoba|Ionatana|Telavi|Apisai|Tavau|Teo|Loto|Pita|Samu|Ioane','Sopoaga|Natano|Teo|Toafa|Italeli|Ielemia|Ionatana|Telavi|Lautasi|Paeniu|Puasau|Latasi|Salesi|Fale|Taufatofua|Malo')
pool('greenlandic','Malik|Aputsiaq|Minik|Inuk|Ivik|Nuka|Pavia|Angut|Kuno|Jens|Hans|Karl|Lars|Ole|Peter|Mikael','Lynge|Rosing|Motzfeldt|Egede|Kleist|Heilmann|Lund|Berthelsen|Petersen|Nielsen|Hansen|Jensen|Olsen|Frederiksen|Kristiansen|Poulsen')
extra={
 'Europe':'Monaco:french;Vatican City:italian;Guernsey:english;Jersey:english;Isle of Man:english',
 'Oceania':'Kiribati:kiribati;Marshall Islands:micronesian;Micronesia:micronesian;Nauru:micronesian;Palau:micronesian;Tuvalu:tuvaluan;Niue:polynesian;Wallis and Futuna:polynesian;Tokelau:polynesian',
 'Asia':'Northern Mariana Islands:filipino',
 'North America':'Greenland:greenlandic;Guadeloupe:french;Martinique:french;Saint Martin:french;Sint Maarten:dutch;Bonaire:dutch;Saint Barthélemy:french;Saint Pierre and Miquelon:french',
 'South America':'French Guiana:french;Falkland Islands:english',
 'Africa':'Réunion:french;Mayotte:swahili;Saint Helena:english'}
for region,content in extra.items():
 for row in content.split(';'):
  name,locale=row.split(':')
  nations.append(dict(id=slug(name),name=name,region=region,playable=False,locales=[dict(pool=locale,weight=100)],clubs=2,cities=[],coverage='authored starter pool; international competition entry separate'))
assert len(nations)==239,len(nations)
assert sum(n['clubs'] for n in nations if n['playable'])==636
out=dict(version=1,name_algorithm='locale-parts-v1',coverage='239 countries and territories, including non-FIFA states; independent from career scenario support or competition entry',sources=[dict(url='https://inside.fifa.com/associations',accessed='2026-09-22',scope='Reference for breadth of football association geography; names, rosters and tuning are authored fictional content.'),dict(url='https://unstats.un.org/unsd/methodology/m49/overview/',accessed='2026-09-22',scope='Country and area identities beyond football membership. Group labels follow game football regions, not UN statistical regions.')],warnings=['Starter name corpora require regional editorial expansion; shared language pools are not exhaustive ethnicity or citizenship models.','Supporting-club names outside authored city lists are fictional geographic-neutral identities.','Population and ability distributions are provisional game tuning, not observed national statistics.'],settings=dict(senior_target=25,youth_target=18,reserve_target=18,free_players_per_nation=12,free_staff_per_nation=9,intake_limit=6,annual_days=365,cycle_days=30,development_days=90,inactive_free_years=2),names=pools,nations=nations)
(ROOT/'data/world_population.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(len(nations),'nations;',len(pools),'name pools;',sum(n['clubs'] for n in nations),'club definitions')
